public enum TipoRescisao {
    SEM_JUSTA_CAUSA,
    POR_JUSTA_CAUSA,
    PEDIDO_DE_DEMISSAO,
    TERMINO_CONTRATO_EXPERIENCIA,
    ACORDO_ENTRE_AS_PARTES,
    RESCISAO_INDIRETA,
    FALECIMENTO_DO_EMPREGADO,
    RESCISAO_POR_CULPA_RECIPROCA
}
